Repository projectsyn/component-vcluster, pull requests merged in 2022-03, with the labels that each got.

#13 Update modulesync config
  .sync.yml
Labels: ignore

#15 Update multi-instance advertisement for Commodore v0.14.0
  class/defaults.yml
Labels: change

#16 Add how-to on configuring OIDC authentication
  docs/modules/ROOT/pages/how-tos/oidc.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation
