Repository projectsyn/component-vcluster, pull requests merged in 2022-08, with the labels that each got.

#27 Allow Renovate to update image tags
  class/defaults.yml
  component/cluster.libsonnet
  component/common.libsonnet
  component/ocp-route.libsonnet
  component/post-setup.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: bug

#28 Update dependency docker.io/bitnami/kubectl to v1.24.3
  class/defaults.yml
  tests/golden/oidc/oidc/oidc/10_cluster.yaml
  tests/golden/openshift/openshift/openshift/10_cluster.yaml
Labels: dependency

#29 Update dependency docker.io/loftsh/vcluster to v0.11.0
  class/defaults.yml
  tests/golden/defaults/defaults/defaults/10_cluster.yaml
  tests/golden/oidc/oidc/oidc/10_cluster.yaml
  tests/golden/openshift/openshift/openshift/10_cluster.yaml
Labels: dependency

#30 Update dependency docker.io/rancher/k3s to v1.24.3
  class/defaults.yml
  tests/golden/defaults/defaults/defaults/10_cluster.yaml
  tests/golden/oidc/oidc/oidc/10_cluster.yaml
  tests/golden/openshift/openshift/openshift/10_cluster.yaml
Labels: dependency

#31 Changes for vcluster dependency upgrades
  component/cluster.libsonnet
  component/coredns.libsonnet
  component/post-setup.libsonnet
  tests/golden/defaults/defaults/defaults/10_cluster.yaml
  tests/golden/oidc/oidc/oidc/10_cluster.yaml
  tests/golden/openshift/openshift/openshift/10_cluster.yaml
Labels: change

#34 Update dependency docker.io/bitnami/kubectl to v1.24.4
  class/defaults.yml
  tests/golden/oidc/oidc/oidc/10_cluster.yaml
  tests/golden/openshift/openshift/openshift/10_cluster.yaml
Labels: dependency
